- delay: 0
  description: ''
  freq_control: true
  frequency: 500.0
  function: Task_blink
  name: blink
  stack: 256
- delay: 0
  description: ''
  freq_control: true
  frequency: 500.0
  function: Task_chassis_main
  name: chassis_main
  stack: 256
- delay: 0
  description: ''
  freq_control: true
  frequency: 500.0
  function: Task_rc_main
  name: rc_main
  stack: 256
- delay: 0
  description: ''
  freq_control: true
  frequency: 500.0
  function: Task_cmd_main
  name: cmd_main
  stack: 256
