/**
 * @file buzzer.h
 * @brief 蜂鸣器设备驱动头文件
 * @details 提供蜂鸣器音频播放功能，支持单音符播放和预设音乐播放
 * @author Generated by STM32CubeMX
 * @date 2025年10月23日
 */

#pragma once

#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ----------------------------------------------------------------- */
#include "bsp/pwm.h"    // PWM底层硬件抽象层
#include "device.h"     // 设备通用头文件
#include <stddef.h>     // 标准定义
#include <stdint.h>     // 标准整型定义

/* USER INCLUDE BEGIN */

/* USER INCLUDE END */

/* Exported constants ------------------------------------------------------- */

/* USER DEFINE BEGIN */

/* USER DEFINE END */

/* Exported types ----------------------------------------------------------- */

/**
 * @brief 音符枚举类型
 * @details 定义标准十二平均律音符，用于音乐播放
 */
typedef enum {
  NOTE_C = 0,       ///< Do音符
  NOTE_CS = 1,      ///< Do#音符 (升Do)
  NOTE_D = 2,       ///< Re音符
  NOTE_DS = 3,      ///< Re#音符 (升Re)
  NOTE_E = 4,       ///< Mi音符
  NOTE_F = 5,       ///< Fa音符
  NOTE_FS = 6,      ///< Fa#音符 (升Fa)
  NOTE_G = 7,       ///< Sol音符
  NOTE_GS = 8,      ///< Sol#音符 (升Sol)
  NOTE_A = 9,       ///< La音符
  NOTE_AS = 10,     ///< La#音符 (升La)
  NOTE_B = 11,      ///< Si音符
  NOTE_REST = 255   ///< 休止符 (无声音)
} NOTE_t;

/**
 * @brief 音调结构体
 * @details 定义一个完整的音调信息，包括音符、八度和持续时间
 */
typedef struct {
  NOTE_t note;          ///< 音符名称 (使用NOTE_t枚举)
  uint8_t octave;       ///< 八度 (0-8，通常使用3-7)
  uint16_t duration_ms; ///< 持续时间，单位毫秒
} Tone_t;

/**
 * @brief 预设音乐枚举类型
 * @details 定义可播放的预设音乐类型
 */
typedef enum {
  /* USER MUSIC MENU BEGIN */
  MUSIC_RM,                        ///< RM 战队队歌
  MUSIC_NOKIA,                     ///< 诺基亚铃声
  MUSIC_FUR_ELISE,                 ///< 贝多芬《致爱丽丝》
  MUSIC_JUE_BIE_SHU,               ///< 《诀别书》
  MUSIC_HONG_DOU,                  ///< 王菲《红豆》
  MUSIC_SHUN,                      ///< 郑润泽《瞬》
  MUSIC_YUAN_YU_CHOU,              ///< 林俊杰《愿与愁》
  MUSIC_DREAM_WEDDING,             ///< 《梦中的婚礼》单线蜂鸣器改编
  MUSIC_FLOWER_DANCE,              ///< DJ Okawari《Flower Dance》
  MUSIC_TORI_NO_UTA,               ///< Lia《鸟之诗》
  MUSIC_GU_SHI_XI_NI,              ///< JJ Lin - Gu Shi Xi Ni
  MUSIC_SENBONZAKURA,              ///< Kurousa-P - Senbonzakura
  MUSIC_YI_BU_ZHI_YAO,             ///< Por Una Cabeza / Yi Bu Zhi Yao
  MUSIC_MOONLIGHT_SONATA,          ///< 贝多芬《月光奏鸣曲》第一乐章
  MUSIC_MOONLIGHT_SONATA_2ND,      ///< 贝多芬《月光奏鸣曲》第二乐章
  MUSIC_MERRY_CHRISTMAS_MR_LAWRENCE, ///< 坂本龙一《圣诞快乐，劳伦斯先生》
  MUSIC_HAPPY_DOU_DI_ZHU_MELODY,   ///< 欢乐斗地主主题曲
  MUSIC_STARTUP_YUAN_YU_CHOU,      ///< Short Yuan Yu Chou startup jingle
  MUSIC_STARTUP_TOMATO_GARDEN,     ///< 番茄花园片段
  MUSIC_STARTUP_BUMBLEBEE,         ///< 《野蜂飞舞》片段
  MUSIC_MOONLIGHT_SONATA_3RD,      ///< 贝多芬《月光奏鸣曲》第三乐章
  /* USER MUSIC MENU END */
} MUSIC_t;

/**
 * @brief 蜂鸣器设备结构体
 * @details 蜂鸣器设备的完整描述，包含设备头信息和PWM通道
 */
typedef struct {
  DEVICE_Header_t header;     ///< 设备通用头信息 (在线状态、时间戳等)
  BSP_PWM_Channel_t channel;  ///< PWM输出通道
} BUZZER_t;

/* USER STRUCT BEGIN */
typedef struct {
  const Tone_t *melody;
  size_t melody_length;
  size_t tone_index;
  uint32_t next_tick;
  uint16_t tone_gap_ms;
  MUSIC_t music;
  bool active;
  bool paused;
  bool loop;
  bool waiting_tone;
  bool waiting_gap;
} BUZZER_MusicPlayer_t;

/* USER STRUCT END */

/* Exported functions prototypes -------------------------------------------- */

/**
 * @brief 初始化蜂鸣器设备
 * @param buzzer 蜂鸣器设备结构体指针
 * @param channel PWM输出通道
 * @return int8_t 返回值：DEVICE_OK(0) 成功，DEVICE_ERR(-1) 失败
 * @note 初始化后蜂鸣器处于停止状态
 */
int8_t BUZZER_Init(BUZZER_t *buzzer, BSP_PWM_Channel_t channel);

/**
 * @brief 启动蜂鸣器播放
 * @param buzzer 蜂鸣器设备结构体指针
 * @return int8_t 返回值：DEVICE_OK(0) 成功，DEVICE_ERR(-1) 失败
 * @note 需要先调用BUZZER_Set设置频率和占空比
 */
int8_t BUZZER_Start(BUZZER_t *buzzer);

/**
 * @brief 停止蜂鸣器播放
 * @param buzzer 蜂鸣器设备结构体指针
 * @return int8_t 返回值：DEVICE_OK(0) 成功，DEVICE_ERR(-1) 失败
 */
int8_t BUZZER_Stop(BUZZER_t *buzzer);

/**
 * @brief 设置蜂鸣器频率和占空比
 * @param buzzer 蜂鸣器设备结构体指针
 * @param freq 频率 (Hz)，通常范围20Hz-20kHz
 * @param duty_cycle 占空比 (0.0-1.0)，影响音量大小
 * @return int8_t 返回值：DEVICE_OK(0) 成功，DEVICE_ERR(-1) 失败
 * @note 设置后需要调用BUZZER_Start才能听到声音
 */
int8_t BUZZER_Set(BUZZER_t *buzzer, float freq, float duty_cycle);

/**
 * @brief 播放预设音乐
 * @param buzzer 蜂鸣器设备结构体指针
 * @param music 音乐类型 (使用MUSIC_t枚举)
 * @return int8_t 返回值：DEVICE_OK(0) 成功，DEVICE_ERR(-1) 失败
 * @note 这是一个阻塞函数，会播放完整首音乐后返回
 */
int8_t BUZZER_PlayMusic(BUZZER_t *buzzer, MUSIC_t music);

/* USER FUNCTION BEGIN */
int8_t BUZZER_MusicPlayerStart(BUZZER_MusicPlayer_t *player,
                                BUZZER_t *buzzer, MUSIC_t music, bool loop,
                                uint32_t now_tick);
int8_t BUZZER_MusicPlayerUpdate(BUZZER_MusicPlayer_t *player,
                                 BUZZER_t *buzzer, uint32_t now_tick);
void BUZZER_MusicPlayerStop(BUZZER_MusicPlayer_t *player, BUZZER_t *buzzer);
void BUZZER_MusicPlayerSilence(BUZZER_MusicPlayer_t *player,
                                BUZZER_t *buzzer);
void BUZZER_MusicPlayerSetPaused(BUZZER_MusicPlayer_t *player,
                                  BUZZER_t *buzzer, bool paused,
                                  uint32_t now_tick);
bool BUZZER_MusicPlayerIsActive(const BUZZER_MusicPlayer_t *player);
bool BUZZER_MusicPlayerIsPaused(const BUZZER_MusicPlayer_t *player);

/* USER FUNCTION END */

#ifdef __cplusplus
}
#endif
