#include "module/autoCtrlAPI/transition/auto_ctrl_transition.h"

#include "module/autoCtrlAPI/transition/auto_ctrl_zone.h"

static const auto_ctrl_transition_t k_auto_ctrl_transition_table[] = {
    {AUTO_CTRL_ZONE_R2_ENTRY, AUTO_CTRL_ZONE_PLATFORM_1,
     AUTO_CTRL_TEMPLATE_ASCEND_400_STD, 0.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, 400},
    {AUTO_CTRL_ZONE_PLATFORM_1, AUTO_CTRL_ZONE_R2_ENTRY,
     AUTO_CTRL_TEMPLATE_DESCEND_400_STD, 0.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, -400},
 
    {AUTO_CTRL_ZONE_PLATFORM_1, AUTO_CTRL_ZONE_PLATFORM_2,
     AUTO_CTRL_TEMPLATE_DESCEND_200_STD, 90.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, -200},
    {AUTO_CTRL_ZONE_PLATFORM_2, AUTO_CTRL_ZONE_PLATFORM_1,
     AUTO_CTRL_TEMPLATE_ASCEND_200_STD, -90.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, 200},
    {AUTO_CTRL_ZONE_PLATFORM_2, AUTO_CTRL_ZONE_PLATFORM_3,
     AUTO_CTRL_TEMPLATE_ASCEND_200_STD, 0.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, 200},
    {AUTO_CTRL_ZONE_PLATFORM_3, AUTO_CTRL_ZONE_PLATFORM_2,
     AUTO_CTRL_TEMPLATE_DESCEND_200_STD, 180.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, -200},
    {AUTO_CTRL_ZONE_PLATFORM_3, AUTO_CTRL_ZONE_PLATFORM_4,
     AUTO_CTRL_TEMPLATE_DESCEND_200_STD, 90.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, -200},
    {AUTO_CTRL_ZONE_PLATFORM_4, AUTO_CTRL_ZONE_PLATFORM_3,
     AUTO_CTRL_TEMPLATE_ASCEND_200_STD, -90.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, 200},
    {AUTO_CTRL_ZONE_PLATFORM_4, AUTO_CTRL_ZONE_PLATFORM_5,
     AUTO_CTRL_TEMPLATE_ASCEND_200_STD, 0.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, 200},
    {AUTO_CTRL_ZONE_PLATFORM_5, AUTO_CTRL_ZONE_PLATFORM_4,
     AUTO_CTRL_TEMPLATE_DESCEND_200_STD, 180.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, -200},
    {AUTO_CTRL_ZONE_PLATFORM_5, AUTO_CTRL_ZONE_PLATFORM_6,
     AUTO_CTRL_TEMPLATE_ASCEND_200_NO_FRONT_SICK, 90.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_BOTTOM_ONLY, 200},
    {AUTO_CTRL_ZONE_PLATFORM_6, AUTO_CTRL_ZONE_PLATFORM_5,
     AUTO_CTRL_TEMPLATE_DESCEND_200_NO_FRONT_SICK, -90.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_BOTTOM_ONLY, -200},
    {AUTO_CTRL_ZONE_PLATFORM_6, AUTO_CTRL_ZONE_PLATFORM_7,
     AUTO_CTRL_TEMPLATE_DESCEND_200_STD, 0.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_BOTTOM_ONLY, -200},
    {AUTO_CTRL_ZONE_PLATFORM_7, AUTO_CTRL_ZONE_PLATFORM_6,
     AUTO_CTRL_TEMPLATE_ASCEND_200_NO_FRONT_SICK, 180.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_BOTTOM_ONLY, 200},
    {AUTO_CTRL_ZONE_PLATFORM_7, AUTO_CTRL_ZONE_PLATFORM_8,
     AUTO_CTRL_TEMPLATE_ASCEND_200_NO_FRONT_SICK, 90.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_BOTTOM_ONLY, 200},
    {AUTO_CTRL_ZONE_PLATFORM_8, AUTO_CTRL_ZONE_PLATFORM_7,
     AUTO_CTRL_TEMPLATE_DESCEND_200_NO_FRONT_SICK, -90.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_BOTTOM_ONLY, -200},
    {AUTO_CTRL_ZONE_PLATFORM_8, AUTO_CTRL_ZONE_PLATFORM_9,
     AUTO_CTRL_TEMPLATE_DESCEND_200_STD, 0.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_BOTTOM_ONLY, -200},
    {AUTO_CTRL_ZONE_PLATFORM_9, AUTO_CTRL_ZONE_PLATFORM_8,
     AUTO_CTRL_TEMPLATE_ASCEND_200_NO_FRONT_SICK, 180.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_BOTTOM_ONLY, 200},
    {AUTO_CTRL_ZONE_PLATFORM_9, AUTO_CTRL_ZONE_PLATFORM_10,
     AUTO_CTRL_TEMPLATE_DESCEND_200_STD, 90.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, -200},
    {AUTO_CTRL_ZONE_PLATFORM_10, AUTO_CTRL_ZONE_PLATFORM_9,
     AUTO_CTRL_TEMPLATE_ASCEND_200_STD, -90.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, 200},
    {AUTO_CTRL_ZONE_PLATFORM_10, AUTO_CTRL_ZONE_PLATFORM_11,
     AUTO_CTRL_TEMPLATE_ASCEND_200_STD, 0.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, 200},
    {AUTO_CTRL_ZONE_PLATFORM_11, AUTO_CTRL_ZONE_PLATFORM_10,
     AUTO_CTRL_TEMPLATE_DESCEND_200_STD, 180.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, -200},
    {AUTO_CTRL_ZONE_PLATFORM_11, AUTO_CTRL_ZONE_PLATFORM_12,
     AUTO_CTRL_TEMPLATE_DESCEND_200_STD, 90.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, -200},
    {AUTO_CTRL_ZONE_PLATFORM_12, AUTO_CTRL_ZONE_PLATFORM_11,
     AUTO_CTRL_TEMPLATE_ASCEND_200_STD, -90.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, 200},

    {AUTO_CTRL_ZONE_PLATFORM_12, AUTO_CTRL_ZONE_R2_EXIT,
     AUTO_CTRL_TEMPLATE_DESCEND_200_STD, 0.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, -200},
    {AUTO_CTRL_ZONE_R2_EXIT, AUTO_CTRL_ZONE_PLATFORM_12,
     AUTO_CTRL_TEMPLATE_ASCEND_200_STD, 180.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, 200},

    {AUTO_CTRL_ZONE_PLATFORM_1, AUTO_CTRL_ZONE_PLATFORM_3,
     AUTO_CTRL_TEMPLATE_FLAT_MOVE, 0.0f, 5.0f, AUTO_CTRL_SENSOR_MODE_YAW_ONLY,
     0},
    {AUTO_CTRL_ZONE_PLATFORM_3, AUTO_CTRL_ZONE_PLATFORM_1,
     AUTO_CTRL_TEMPLATE_FLAT_MOVE, 180.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_YAW_ONLY, 0},
    {AUTO_CTRL_ZONE_PLATFORM_5, AUTO_CTRL_ZONE_PLATFORM_7,
     AUTO_CTRL_TEMPLATE_FLAT_MOVE, 0.0f, 5.0f, AUTO_CTRL_SENSOR_MODE_YAW_ONLY,
     0},
    {AUTO_CTRL_ZONE_PLATFORM_7, AUTO_CTRL_ZONE_PLATFORM_5,
     AUTO_CTRL_TEMPLATE_FLAT_MOVE, 180.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_YAW_ONLY, 0},
    {AUTO_CTRL_ZONE_PLATFORM_9, AUTO_CTRL_ZONE_PLATFORM_11,
     AUTO_CTRL_TEMPLATE_FLAT_MOVE, 0.0f, 5.0f, AUTO_CTRL_SENSOR_MODE_YAW_ONLY,
     0},
    {AUTO_CTRL_ZONE_PLATFORM_11, AUTO_CTRL_ZONE_PLATFORM_9,
     AUTO_CTRL_TEMPLATE_FLAT_MOVE, 180.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_YAW_ONLY, 0},
    {AUTO_CTRL_ZONE_PLATFORM_2, AUTO_CTRL_ZONE_PLATFORM_4,
     AUTO_CTRL_TEMPLATE_FLAT_MOVE, 0.0f, 5.0f, AUTO_CTRL_SENSOR_MODE_YAW_ONLY,
     0},
    {AUTO_CTRL_ZONE_PLATFORM_4, AUTO_CTRL_ZONE_PLATFORM_2,
     AUTO_CTRL_TEMPLATE_FLAT_MOVE, 180.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_YAW_ONLY, 0},
    {AUTO_CTRL_ZONE_PLATFORM_10, AUTO_CTRL_ZONE_PLATFORM_12,
     AUTO_CTRL_TEMPLATE_FLAT_MOVE, 0.0f, 5.0f, AUTO_CTRL_SENSOR_MODE_YAW_ONLY,
     0},
    {AUTO_CTRL_ZONE_PLATFORM_12, AUTO_CTRL_ZONE_PLATFORM_10,
     AUTO_CTRL_TEMPLATE_FLAT_MOVE, 180.0f, 5.0f,
     AUTO_CTRL_SENSOR_MODE_YAW_ONLY, 0},
};

const auto_ctrl_transition_t *AutoCtrlTransition_Find(auto_ctrl_zone_e from,
                                                      auto_ctrl_zone_e to) {
  if (!AutoCtrlZone_IsValid(from) || !AutoCtrlZone_IsValid(to)) {
    return 0;
  }

  for (uint32_t i = 0;
       i < (uint32_t)(sizeof(k_auto_ctrl_transition_table) /
                      sizeof(k_auto_ctrl_transition_table[0]));
       i++) {
    const auto_ctrl_transition_t *transition = &k_auto_ctrl_transition_table[i];
    if (transition->from_zone == from && transition->to_zone == to) {
      return transition;
    }
  }

  return 0;
}

bool AutoCtrlTransition_IsLegal(auto_ctrl_zone_e from, auto_ctrl_zone_e to) {
  return AutoCtrlTransition_Find(from, to) != 0;
}