#include "module/autoCtrlAPI/transition/auto_ctrl_transition.h"

/*
 * auto_ctrl_transition.c
 *
 * 作用：
 * - 维护区块转移表（from_zone -> to_zone）；
 * - 对外提供“查找转移定义”和“是否合法”接口。
 *
 * 设计原则：
 * - 只允许表中声明过的邻接转移；
 * - 不允许通过本模块自动推导跨级/对角跳转；
 * - 每条表项绑定模板、姿态要求和传感器模式。
 */

#include "module/autoCtrlAPI/transition/auto_ctrl_zone.h"

#define AUTO_CTRL_PI_RAD (3.14159265358979323846f)
#define AUTO_CTRL_PI_2_RAD (1.57079632679489661923f)
#define AUTO_CTRL_YAW_0_RAD (0.0f)
#define AUTO_CTRL_YAW_POS_90_RAD (0.0f)
#define AUTO_CTRL_YAW_NEG_90_RAD (-0.0f)
#define AUTO_CTRL_YAW_180_RAD (AUTO_CTRL_PI_RAD)
#define AUTO_CTRL_YAW_TOLERANCE_RAD (0.08726646259971647884f)

/*
 * 转移表：
 * - Entry/Exit 与平台区块之间的上下台阶关系；
 * - 平台网格内邻接移动关系；
 * - 每条关系显式声明模板与传感器约束。
 */
static const auto_ctrl_transition_t k_auto_ctrl_transition_table[] = {
  /* Entry blocks to top row platforms. No entry-entry transitions. */
  {AUTO_CTRL_ZONE_R2_ENTRY1, AUTO_CTRL_ZONE_PLATFORM_1,
  AUTO_CTRL_TEMPLATE_ASCEND_400_STD, AUTO_CTRL_YAW_POS_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, 400},
  {AUTO_CTRL_ZONE_PLATFORM_1, AUTO_CTRL_ZONE_R2_ENTRY1,
  AUTO_CTRL_TEMPLATE_DESCEND_400_STD, AUTO_CTRL_YAW_NEG_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, -400},

  {AUTO_CTRL_ZONE_R2_ENTRY2, AUTO_CTRL_ZONE_PLATFORM_2,
  AUTO_CTRL_TEMPLATE_ASCEND_200, AUTO_CTRL_YAW_POS_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, 200},
  {AUTO_CTRL_ZONE_PLATFORM_2, AUTO_CTRL_ZONE_R2_ENTRY2,
  AUTO_CTRL_TEMPLATE_DESCEND_200, AUTO_CTRL_YAW_NEG_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, -200},

  {AUTO_CTRL_ZONE_R2_ENTRY3, AUTO_CTRL_ZONE_PLATFORM_3,
  AUTO_CTRL_TEMPLATE_ASCEND_400_STD, AUTO_CTRL_YAW_POS_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, 400},
  {AUTO_CTRL_ZONE_PLATFORM_3, AUTO_CTRL_ZONE_R2_ENTRY3,
  AUTO_CTRL_TEMPLATE_DESCEND_400_STD, AUTO_CTRL_YAW_NEG_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, -400},

  /* Platform 1..12: only adjacent orthogonal moves, no diagonal moves. */
  {AUTO_CTRL_ZONE_PLATFORM_1, AUTO_CTRL_ZONE_PLATFORM_2,
  AUTO_CTRL_TEMPLATE_DESCEND_200, AUTO_CTRL_YAW_0_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, -200},
  {AUTO_CTRL_ZONE_PLATFORM_2, AUTO_CTRL_ZONE_PLATFORM_1,
  AUTO_CTRL_TEMPLATE_ASCEND_200, AUTO_CTRL_YAW_180_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, 200},
  {AUTO_CTRL_ZONE_PLATFORM_2, AUTO_CTRL_ZONE_PLATFORM_3,
  AUTO_CTRL_TEMPLATE_ASCEND_200, AUTO_CTRL_YAW_0_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, 200},
  {AUTO_CTRL_ZONE_PLATFORM_3, AUTO_CTRL_ZONE_PLATFORM_2,
  AUTO_CTRL_TEMPLATE_DESCEND_200, AUTO_CTRL_YAW_180_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, -200},

  {AUTO_CTRL_ZONE_PLATFORM_1, AUTO_CTRL_ZONE_PLATFORM_4,
  AUTO_CTRL_TEMPLATE_DESCEND_200, AUTO_CTRL_YAW_POS_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, -200},
  {AUTO_CTRL_ZONE_PLATFORM_4, AUTO_CTRL_ZONE_PLATFORM_1,
  AUTO_CTRL_TEMPLATE_ASCEND_200, AUTO_CTRL_YAW_NEG_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, 200},
  {AUTO_CTRL_ZONE_PLATFORM_2, AUTO_CTRL_ZONE_PLATFORM_5,
  AUTO_CTRL_TEMPLATE_ASCEND_200, AUTO_CTRL_YAW_POS_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, 200},
  {AUTO_CTRL_ZONE_PLATFORM_5, AUTO_CTRL_ZONE_PLATFORM_2,
  AUTO_CTRL_TEMPLATE_DESCEND_200, AUTO_CTRL_YAW_NEG_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, -200},
  {AUTO_CTRL_ZONE_PLATFORM_3, AUTO_CTRL_ZONE_PLATFORM_6,
  AUTO_CTRL_TEMPLATE_ASCEND_200, AUTO_CTRL_YAW_POS_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_BOTTOM_ONLY, 200},
  {AUTO_CTRL_ZONE_PLATFORM_6, AUTO_CTRL_ZONE_PLATFORM_3,
  AUTO_CTRL_TEMPLATE_DESCEND_200, AUTO_CTRL_YAW_NEG_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_BOTTOM_ONLY, -200},

  {AUTO_CTRL_ZONE_PLATFORM_4, AUTO_CTRL_ZONE_PLATFORM_5,
  AUTO_CTRL_TEMPLATE_ASCEND_200, AUTO_CTRL_YAW_0_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, 200},
  {AUTO_CTRL_ZONE_PLATFORM_5, AUTO_CTRL_ZONE_PLATFORM_4,
  AUTO_CTRL_TEMPLATE_DESCEND_200, AUTO_CTRL_YAW_180_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, -200},
  {AUTO_CTRL_ZONE_PLATFORM_5, AUTO_CTRL_ZONE_PLATFORM_6,
  AUTO_CTRL_TEMPLATE_ASCEND_200, AUTO_CTRL_YAW_0_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_BOTTOM_ONLY, 200},
  {AUTO_CTRL_ZONE_PLATFORM_6, AUTO_CTRL_ZONE_PLATFORM_5,
  AUTO_CTRL_TEMPLATE_DESCEND_200, AUTO_CTRL_YAW_180_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_BOTTOM_ONLY, -200},

  {AUTO_CTRL_ZONE_PLATFORM_4, AUTO_CTRL_ZONE_PLATFORM_7,
  AUTO_CTRL_TEMPLATE_ASCEND_200, AUTO_CTRL_YAW_POS_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, 200},
  {AUTO_CTRL_ZONE_PLATFORM_7, AUTO_CTRL_ZONE_PLATFORM_4,
  AUTO_CTRL_TEMPLATE_DESCEND_200, AUTO_CTRL_YAW_NEG_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, -200},
  {AUTO_CTRL_ZONE_PLATFORM_5, AUTO_CTRL_ZONE_PLATFORM_8,
  AUTO_CTRL_TEMPLATE_ASCEND_200, AUTO_CTRL_YAW_POS_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_BOTTOM_ONLY, 200},
  {AUTO_CTRL_ZONE_PLATFORM_8, AUTO_CTRL_ZONE_PLATFORM_5,
  AUTO_CTRL_TEMPLATE_DESCEND_200, AUTO_CTRL_YAW_NEG_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_BOTTOM_ONLY, -200},
  {AUTO_CTRL_ZONE_PLATFORM_6, AUTO_CTRL_ZONE_PLATFORM_9,
  AUTO_CTRL_TEMPLATE_DESCEND_200, AUTO_CTRL_YAW_POS_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_BOTTOM_ONLY, -200},
  {AUTO_CTRL_ZONE_PLATFORM_9, AUTO_CTRL_ZONE_PLATFORM_6,
  AUTO_CTRL_TEMPLATE_ASCEND_200, AUTO_CTRL_YAW_NEG_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_BOTTOM_ONLY, 200},

  {AUTO_CTRL_ZONE_PLATFORM_7, AUTO_CTRL_ZONE_PLATFORM_8,
  AUTO_CTRL_TEMPLATE_ASCEND_200, AUTO_CTRL_YAW_0_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_BOTTOM_ONLY, 200},
  {AUTO_CTRL_ZONE_PLATFORM_8, AUTO_CTRL_ZONE_PLATFORM_7,
  AUTO_CTRL_TEMPLATE_DESCEND_200, AUTO_CTRL_YAW_180_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_BOTTOM_ONLY, -200},
  {AUTO_CTRL_ZONE_PLATFORM_8, AUTO_CTRL_ZONE_PLATFORM_9,
  AUTO_CTRL_TEMPLATE_DESCEND_200, AUTO_CTRL_YAW_0_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_BOTTOM_ONLY, -200},
  {AUTO_CTRL_ZONE_PLATFORM_9, AUTO_CTRL_ZONE_PLATFORM_8,
  AUTO_CTRL_TEMPLATE_ASCEND_200, AUTO_CTRL_YAW_180_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_BOTTOM_ONLY, 200},

  {AUTO_CTRL_ZONE_PLATFORM_7, AUTO_CTRL_ZONE_PLATFORM_10,
  AUTO_CTRL_TEMPLATE_DESCEND_200, AUTO_CTRL_YAW_POS_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, -200},
  {AUTO_CTRL_ZONE_PLATFORM_10, AUTO_CTRL_ZONE_PLATFORM_7,
  AUTO_CTRL_TEMPLATE_ASCEND_200, AUTO_CTRL_YAW_NEG_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, 200},
  {AUTO_CTRL_ZONE_PLATFORM_8, AUTO_CTRL_ZONE_PLATFORM_11,
  AUTO_CTRL_TEMPLATE_DESCEND_200, AUTO_CTRL_YAW_POS_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_BOTTOM_ONLY, -200},
  {AUTO_CTRL_ZONE_PLATFORM_11, AUTO_CTRL_ZONE_PLATFORM_8,
  AUTO_CTRL_TEMPLATE_ASCEND_200, AUTO_CTRL_YAW_NEG_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_BOTTOM_ONLY, 200},
  {AUTO_CTRL_ZONE_PLATFORM_9, AUTO_CTRL_ZONE_PLATFORM_12,
  AUTO_CTRL_TEMPLATE_DESCEND_200, AUTO_CTRL_YAW_POS_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, -200},
  {AUTO_CTRL_ZONE_PLATFORM_12, AUTO_CTRL_ZONE_PLATFORM_9,
  AUTO_CTRL_TEMPLATE_ASCEND_200, AUTO_CTRL_YAW_NEG_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, 200},

  {AUTO_CTRL_ZONE_PLATFORM_10, AUTO_CTRL_ZONE_PLATFORM_11,
  AUTO_CTRL_TEMPLATE_ASCEND_200, AUTO_CTRL_YAW_0_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, 200},
  {AUTO_CTRL_ZONE_PLATFORM_11, AUTO_CTRL_ZONE_PLATFORM_10,
  AUTO_CTRL_TEMPLATE_DESCEND_200, AUTO_CTRL_YAW_180_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, -200},
  {AUTO_CTRL_ZONE_PLATFORM_11, AUTO_CTRL_ZONE_PLATFORM_12,
  AUTO_CTRL_TEMPLATE_DESCEND_200, AUTO_CTRL_YAW_0_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, -200},
  {AUTO_CTRL_ZONE_PLATFORM_12, AUTO_CTRL_ZONE_PLATFORM_11,
  AUTO_CTRL_TEMPLATE_ASCEND_200, AUTO_CTRL_YAW_180_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, 200},

  /* Bottom row platforms to exit blocks. No exit-exit transitions. */
  {AUTO_CTRL_ZONE_PLATFORM_10, AUTO_CTRL_ZONE_R2_EXIT1,
  AUTO_CTRL_TEMPLATE_DESCEND_200, AUTO_CTRL_YAW_POS_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, -200},
  {AUTO_CTRL_ZONE_R2_EXIT1, AUTO_CTRL_ZONE_PLATFORM_10,
  AUTO_CTRL_TEMPLATE_ASCEND_200, AUTO_CTRL_YAW_NEG_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, 200},

  {AUTO_CTRL_ZONE_PLATFORM_11, AUTO_CTRL_ZONE_R2_EXIT2,
  AUTO_CTRL_TEMPLATE_DESCEND_400_STD, AUTO_CTRL_YAW_POS_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, -400},
  {AUTO_CTRL_ZONE_R2_EXIT2, AUTO_CTRL_ZONE_PLATFORM_11,
  AUTO_CTRL_TEMPLATE_ASCEND_400_STD, AUTO_CTRL_YAW_NEG_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, 400},

  {AUTO_CTRL_ZONE_PLATFORM_12, AUTO_CTRL_ZONE_R2_EXIT3,
  AUTO_CTRL_TEMPLATE_DESCEND_200, AUTO_CTRL_YAW_POS_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, -200},
  {AUTO_CTRL_ZONE_R2_EXIT3, AUTO_CTRL_ZONE_PLATFORM_12,
  AUTO_CTRL_TEMPLATE_ASCEND_200, AUTO_CTRL_YAW_NEG_90_RAD,
  AUTO_CTRL_YAW_TOLERANCE_RAD,
   AUTO_CTRL_SENSOR_MODE_SICK_FRONT_AND_BOTTOM, 200},
};

/* 顺序扫描转移表，命中 from/to 则返回对应表项。 */
const auto_ctrl_transition_t *AutoCtrlTransition_Find(auto_ctrl_zone_e from,
                                                      auto_ctrl_zone_e to) {
  if (!AutoCtrlZone_IsValid(from) || !AutoCtrlZone_IsValid(to)) {
    return 0;
  }

  for (uint32_t i = 0;
       i < (uint32_t)(sizeof(k_auto_ctrl_transition_table) /
                      sizeof(k_auto_ctrl_transition_table[0]));
       i++) {
    const auto_ctrl_transition_t *transition = &k_auto_ctrl_transition_table[i];
    if (transition->from_zone == from && transition->to_zone == to) {
      return transition;
    }
  }

  return 0;
}

/* 转移合法性判定：查表成功即合法。 */
bool AutoCtrlTransition_IsLegal(auto_ctrl_zone_e from, auto_ctrl_zone_e to) {
  return AutoCtrlTransition_Find(from, to) != 0;
}